# Generated by Django 5.2.8 on 2025-11-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('name', 'location')},
        ),
    ]
